name: Android CI
# Controlls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  # Allows you to run this workflow from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
        
      
      - name: Run Lint
        run: ./gradlew lint
      
      
      - name: Generate Lint Report artifact
        run: mv app/build/reports/lint-results-debug.html lint-report.html
      
      - name: Upload Lint Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Lint report
          path: lint-report.html
    
  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: action/checkout@v3
      
      - name: Run tests
        run: ./gradlew test
      
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: Unit test report
          path: app/build/reports/tests/testDebugUnitTest

    
  build:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks out repository under $GITHUB_WORKSPACE so job can access it
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
      # Runsa single command using the runner shell 
    - name: Run a one-line script
      run: echo Hello, World!
      # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
