name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
        
      - name: Run Lint
        run: ./gradlew lint
      
      - name: Generate Lint Report artifact
        run: mv app/build/reports/lint-results-debug.html lint-report.html
      
      - name: Upload Lint Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Lint report
          path: lint-report.html
    
  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      
      - name: Run tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/test/testDebugUnitTest/


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
